[package]
name = "bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints]
workspace = true

[dependencies]
package = {path = "../package"}
httpsearch = {path = "../httpsearch"}
fssearch = { path = "../fssearch" }
bpmutil = { path = "../bpmutil" }

anyhow = { workspace = true }
blake3 = { workspace = true }
camino = { workspace = true, features = ["serde1"]}
chrono = { workspace = true, features = ["serde"]}
clap = { workspace = true }
regex = { workspace = true }
semver = { workspace = true }
serde = { workspace = true, features = ["derive"]}
serde_derive = { workspace = true }
serde_json = { workspace = true }
tabwriter = { workspace = true }
tar = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
walkdir = { workspace = true }
zstd = { workspace = true, features = ["zstdmt"]}

itertools = "0.10.5"
version-compare = "0.1.1"
humantime = "2.1.0"

[features]
default = []
