[package]
name = "bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
package = {path = "../package"}
httpsearch = {path = "../httpsearch"}
fssearch = { path = "../fssearch" }
#hash_stream = {path = "../hash_stream"}
anyhow = "1.0.68"
blake2 = "0.9.1"
clap = "4.0.32"
itertools = "0.10.5"
regex = "1.7.0"
semver = "1.0.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
tabwriter = "1.2.1"
tar = "0.4.38"
toml = { version = "0.5.10", features = ["preserve_order"] }
walkdir = "2.3.2"
zstd = "0.12.1"
serde_yaml = "0.9.21"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
version-compare = "0.1.1"
sha2 = "0.10.7"
serde_json = "1.0.100"
rmp-serde = "1.1.2"

#ignore = "0.4.18" # .gitignore style matching
#flate2 = "1.0"

[features]
default = []
