[package]
name = "bpm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#hash_stream = {path = "../hash_stream"}
#flate2 = "1.0"
#ignore = "0.4.18" # .gitignore style matching
#sha2 = "0.10.6"
package = {path = "../package"}
#flate2 = "1.0"
httpsearch = {path = "../httpsearch"}
anyhow = "1.0.68"
blake2 = "0.9.1"
clap = "4.0.32"
itertools = "0.10.5"
regex = "1.7.0"
#ron = "0.8.0"
semver = "1.0.14"
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
tabwriter = "1.2.1"
tar = "0.4.38"
toml = { version = "0.5.10", features = ["preserve_order"] }
walkdir = "2.3.2"
zstd = "0.12.1"
serde_yaml = "0.9.21"
