cache_dir = "${BPM}/../../crates/bpm/cache"
database = "${BPM}/../../crates/bpm/db.yaml"
use_default_target = true

[providers]
main = "http://localhost:8000/pkg"

[mount]
TARGET = "${BPM}/../../crates/bpm/install"
EXTENSIONS = "${BPM}/../../crates/bpm/install/extensions"
