database = "${BPM}/../../crates/bpm/db.json"

[cache]
dir = "${BPM}/../../crates/bpm/cache"
retention = "10mins"

[mount]
TARGET = { default = true, path = "${THIS}/crates/bpm/install/target" }
TEST  = "${THIS}/crates/bpm/install/test"

[providers]
test1 = "http://localhost:8000/pkg/"
test2 = "file://${THIS}/crates/bpmpack/pkg/"
