[workspace]
resolver = "2"

members = [
    "crates/bpm",
    "crates/bpmd",
    "crates/bpmpack",
    "crates/hash_stream",
    "crates/hashdir",
    "crates/httpsearch",
    "crates/package",
    "crates/walk_example",
    "crates/zstd_patch",
]
