[package]
name = "walk_example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
tabwriter = "1.2.1"
walkdir = "2.3.3"

[features]
default = ["color"]
color = []
