[package]
name = "version"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true }
version-compare = { workspace = true }
