[package]
name = "version"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bpm_version_compare.path = "../bpm_version_compare"
semver = { workspace = true, features = ["serde"] }
serde = { workspace = true }

[dev-dependencies]
version-compare = "0.2.0"
