[package]
name = "hashdir"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
blake3 = {workspace = true}

jwalk = "0.8.1"
rayon = "1.7.0"
