[package]
name = "bpm_version_compare"
version = "0.1.0"
edition = "2024"

[lib]
name = "bpm_version_compare"
path = "src/lib.rs"

[[bin]]
name = "bpm_version_compare"
path = "src/main.rs"

[dependencies]
semver = { version = "1.0.26", optional = true }

[features]
semver = ["dep:semver"]
