[package]
name = "zstd_patch"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[features]

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
zstd = { workspace = true, features = ["experimental", "zstdmt"] }

bytesize = "1.1.0"
indicatif = "0.17.3"

