[package]
name = "bpmpack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
package = {"path" = "../package"}
anyhow = "1.0.71"
blake2 = "0.9.1"
clap = "4.0.32"
#clap = "2.33.3"
flate2 = "1.0"
ignore = "0.4.20"
indicatif = "0.17.3"
#ignore = "0.4.18" # .gitignore style matching
semver = "1.0.14"
sha2 = "0.10.6"
#semver = "0.9.0"
tar = "0.4.38"
zstd = { version = "0.12.1", features = ["zstdmt"] }
toml = { version = "0.5.10", features = ["preserve_order"] }


[features]
default = ["mt"]
mt = []
