[package]
name = "package"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
serde = { version = "1.0.163", features = ["derive"] }
serde_derive = "1.0.163"
tar = "0.4.38"
zstd = "0.12.3"
toml = { version = "0.7.4", features = ["preserve_order"], optional = true}
serde_yaml = { version = "0.9.21", optional = true }

[features]
default = ["yaml"]
toml = ["dep:toml"]
yaml = ["dep:serde_yaml"]
